-- insert into alien values (101,'Navin','Java');
-- insert into alien values (102,'Kiran','Android');
-- insert into alien values (103,'Pravin','Python');
-- insert into alien values (104,'Komal','Java');
-- insert into alien values (105,'Rafiq','Android');

-- insert into admin values (101,'Dhanu@gmail.com','Dhanu');
-- insert into admin values (102,'Dhanuk@gmail.com','Dhanuk');
-- insert into admin values (103,'Dhan@gmail.com','Dhan');
-- insert into admin values (104,'Dh@gmail.com','Dh');
-- insert into admin values (105,'Dhanuka@gmail.com','Dhanuka');
